spring.application.name=experiment7

server.port=8080

spring.datasource.url=jdbc:h2:mem:rbacdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.security=INFO
